## 2. NumPy 基础

### 2.1 NumPy 数组对象

`ndarray`: NumPy中的多维数组对象。

* 由**实际数据**和**元数据**组成。

* 大部分数组操作改变的是元数据。

* NumPy数组一般是同质的：所有元素类型一致。

使用`arange()`创建数组：

> `arange()`创建一个值平均分布的数组。

In [1]:
import numpy as np
a = np.arange(5)

使用`dtype()`查看数组的数据类型：

> `ndarray.dtype`是ndarray数组的数据类型。

In [2]:
a.dtype

dtype('int32')

使用`shape`查看数组的维度：

> `ndarray.shape`是一个tuple，tuple中的元素即为这个数组在每一个维度上的大小。

In [3]:
a.shape

(5,)

### 2.2 创建多维数组

#### 创建多维数组，并显示其维度：

> `array()`函数根据给定的对象生成NumPy数组。给定的对象应该是“类数组”的(array-like)。Python中的list就可以。

In [4]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [5]:
m.shape

(2, 2)

创建一个3×3多维数组：

In [6]:
mat = np.array([np.arange(3), np.arange(3), np.arange(3)])
mat

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [7]:
mat.shape

(3, 3)

选取数组中的某个特定元素：

> 注意：使用`a[m,n]`选取，而不是像python list那样用`a[m][n]`选取。

In [8]:
a = np.array([ [1, 2], [3, 4] ])
a

array([[1, 2],
       [3, 4]])

In [9]:
(a[1,0], a[1,1])

(3, 4)

#### 数据类型

很多函数的参数中可以使用可选的`dtype`指定数据类型：

In [10]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

数据类型对象是`numpy.dtype`类的实例。

> 通过数组的`dtype`属性的`itemsize`属性，可以给出数组的单个元素在内存中占用的字节数

In [11]:
a.dtype.itemsize

4

可以使用字符自定义数据类型。

> 完整的NumPy数据类型列表可以使用`sctypeDict.keys()`查看：

In [12]:
np.sctypeDict.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 'short', 10, 11, 'ubyte', 13, 14, 15, 'longdouble', 17, 18, 19, 20, 21, 'bool', 23, 'clongfloat', 'unicode', 'm8', 'float', 'singlecomplex', 'double', 'UInt16', 'complex_', 'h', 'str', 'P', 'intp', 'complex128', 'g', 'O', 'longlong', 'void', 'int16', 'Complex32', 'timedelta64', 'cdouble', 9, 'I', 'uintc', 'Str0', 'D', 'str0', 'float64', 'u4', 'f', 12, 'Timedelta64', 'i1', 'float32', 'byte', 'Void0', 'u1', 'Object0', 'm', 'csingle', 'intc', 'int0', 'void0', 'uint16', 'V', 16, 'Float64', 'e', 'uint32', '?', 'S', 'uint8', 'bytes0', 'c16', 'uint', 'i2', 'Int32', 'clongdouble', 'u8', 'float_', 'int8', 'object0', 'L', 'Float16', 'd', 22, 'Int64', 'Bool', 'i8', 'H', 'UInt8', 'uint64', 'i4', 'Q', 'string_', 'p', 'G', 'i', 'uintp', 'Bytes0', 'bytes_', 'longfloat', 'b', 'object_', 'unicode_', 'M8', 'Float32', 'complex64', 'a', 'B', 'int64', 'long', 'str_', 'Int16', 'bool_', 'f8', 'f4', 'M', 'u2', 'c8', 'float16', 'longcomplex', 'Datetime64', 'ulonglong', 'ob

> dtype类的字符编码可以用它的`char`属性获得，不过通常不建议使用字符编码。

In [13]:
t = np.dtype('float32')
t.char

'f'

`dtype`和`np.{type}`类型有微妙的差别，但可以认为`np.{type}`只是快速访问`dtype`的方式。见[NumPy文档的说明](http://docs.scipy.org/doc/numpy/user/basics.types.html)：

In [14]:
[type(np.float32), type(np.dtype('float32'))]

[type, numpy.dtype]

In [15]:
float_arr1 = np.arange(3, dtype=np.float32)
float_arr2 = np.arange(3, dtype=np.dtype('float32'))

In [16]:
float_arr1.dtype is float_arr2.dtype

True