## 2. NumPy 基础

### 2.1 NumPy 数组对象

`ndarray`: NumPy中的多维数组对象。

* 由**实际数据**和**元数据**组成。

* 大部分数组操作改变的是元数据。

* NumPy数组一般是同质的：所有元素类型一致。

使用`arange()`创建数组：

> `arange()`创建一个值平均分布的数组。

In [1]:
import numpy as np
a = np.arange(5)

使用`dtype()`查看数组的数据类型：

> `ndarray.dtype`是ndarray数组的数据类型。

In [2]:
a.dtype

dtype('int32')

使用`shape`查看数组的维度：

> `ndarray.shape`是一个tuple，tuple中的元素即为这个数组在每一个维度上的大小。

In [3]:
a.shape

(5,)

### 2.2 创建多维数组

#### 创建多维数组，并显示其维度：

> `array()`函数根据给定的对象生成NumPy数组。给定的对象应该是“类数组”的(array-like)。Python中的list就可以。

In [4]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [5]:
m.shape

(2, 2)

创建一个3×3多维数组：

In [6]:
mat = np.array([np.arange(3), np.arange(3), np.arange(3)])
mat

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [7]:
mat.shape

(3, 3)

选取数组中的某个特定元素：

> 注意：使用`a[m,n]`选取，而不是像python list那样用`a[m][n]`选取。

In [8]:
a = np.array([ [1, 2], [3, 4] ])
a

array([[1, 2],
       [3, 4]])

In [19]:
(a[1,0], a[1,1])

(3, 4)

#### 数据类型

很多函数的参数中可以使用可选的`dtype`指定数据类型：

In [14]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

数据类型对象是`numpy.dtype`类的实例。

> 通过数组的`dtype`属性的`itemsize`属性，可以给出数组的单个元素在内存中占用的字节数

In [18]:
a.dtype.itemsize

4

可以使用字符自定义数据类型。

> 完整的NumPy数据类型列表可以使用`sctypeDict.keys()`查看：

In [21]:
np.sctypeDict.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 'q', 8, 9, 10, 11, 12, 'V', 14, 15, 16, 17, 18, 19, 20, 21, 22, 'Q', 'single', 'str', 'Timedelta64', 'datetime64', 'complex', 'short', 'singlecomplex', 'int16', 'cfloat', 7, 'int0', 'UInt64', 'ushort', 'longlong', 'Complex32', 'Float16', 'c16', 'uintc', 'double', 'Bool', 'float16', 'uint32', 'c8', 'csingle', 'f', 'bytes', 'Int16', 'uint', 'Datetime64', 'ubyte', 'u2', 'l', 'void', 'm8', 'float_', 'int_', 'byte', 'u1', 'a', 'p', 'f4', 'timedelta64', 'Int32', 'b1', 'u4', 'object0', 'd', 'L', 'int64', 'i', 'half', 'F', 'G', '?', 'complex128', 'string_', 'f2', 'U', 'I', 13, 'clongdouble', 'unicode_', 'Bytes0', 'intc', 'float32', 'bool8', 'P', 23, 'longfloat', 'Str0', 'g', 'str_', 'UInt16', 'uint64', 'longcomplex', 'bytes_', 'uint0', 'h', 'Float64', 'H', 'void0', 'float', 'int32', 'm', 'Object0', 'complex_', 'bool', 'unicode', 'float64', 'bytes0', 'clongfloat', 'B', 'intp', 'object', 'S', 'int8', 'i2', 'ulonglong', 'M', 'object_', 'i1', 'i8', 'UInt8', 'Int64',

> dtype类的字符编码可以用它的`char`属性获得，不过通常不建议使用字符编码。

In [31]:
t = np.dtype('float32')
t.char

'f'

`dtype`和`np.{type}`类型有微妙的差别，但可以认为`np.{type}`只是快速访问`dtype`的方式。见[NumPy文档的说明](http://docs.scipy.org/doc/numpy/user/basics.types.html)：

In [45]:
[type(np.float32), type(np.dtype('float32'))]

[type, numpy.dtype]

In [42]:
float_arr1 = np.arange(3, dtype=np.float32)
float_arr2 = np.arange(3, dtype=np.dtype('float32'))

In [44]:
float_arr1.dtype is float_arr2.dtype

True