Jupyter Notebook Themes using [jupyter-themes](https://github.com/dunovank/jupyter-themes):

```
jt -t oceans16 -T -alt -f fira -nf robotosans -tf notoserif -tfs 12
```

Below: note reading *NumPy Beginner's Guide*. 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
# Apply jupyter-themes' theme on matplotlib
from jupyterthemes import jtplot
jtplot.style(context='notebook')

In [5]:
help(np.savetxt)

Help on function savetxt in module numpy.lib.npyio:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
            a) a single specifier, `fmt='%.4e'`, resulting in numbers formatted
                like `' (%s+%sj)' % (fmt, fmt)`
            b) a full string specifying every real and imaginary part, e.g.
                `' %.4e %+.4ej %.4e %+.4ej 

In [6]:
np.savetxt('eye.txt', e)

In [7]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%rub

In [8]:
!more eye.txt

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00
1.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00


In [9]:
!more data.csv

AAPL,28-01-2011, ,344.17,344.4,333.53,336.1,21144800
AAPL,31-01-2011, ,335.8,340.04,334.3,339.32,13473000
AAPL,01-02-2011, ,341.3,345.65,340.98,345.03,15236800
AAPL,02-02-2011, ,344.45,345.25,343.55,344.32,9242600
AAPL,03-02-2011, ,343.8,344.24,338.55,343.44,14064100
AAPL,04-02-2011, ,343.61,346.7,343.51,346.5,11494200
AAPL,07-02-2011, ,347.89,353.25,347.64,351.88,17322100
AAPL,08-02-2011, ,353.68,355.52,352.15,355.2,13608500
AAPL,09-02-2011, ,355.19,359,354.87,358.16,17240800
AAPL,10-02-2011, ,357.39,360,348,354.54,33162400
AAPL,11-02-2011, ,354.75,357.8,353.54,356.85,13127500
AAPL,14-02-2011, ,356.79,359.48,356.71,359.18,11086200
AAPL,15-02-2011, ,359.19,359.97,357.55,359.9,10149000
AAPL,16-02-2011, ,360.8,364.9,360.5,363.13,17184100
AAPL,17-02-2011, ,357.1,360.27,356.52,358.3,18949000
AAPL,18-02-2011, ,358.21,359.5,349.52,350.56,29144500
AAPL,22-02-2011, ,342.05,345.4,337.72,338.61,31162200
AAPL,23-02-2011, ,338.77,344.64,338.61,342.62,23994700
AAPL,24-02-2011, ,344.02,345.15,338.37

In [10]:
help(np.loadtxt)

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence, optional
        The characters or list o

In [11]:
c, v = np.loadtxt('data.csv', delimiter=',', usecols=(6, 7), unpack=True)
print('c = %r \n v = %r' % (c, v))

c = array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67,  351.99]) 
 v = array([ 21144800.,  13473000.,  15236800.,   9242600.,  14064100.,
        11494200.,  17322100.,  13608500.,  17240800.,  33162400.,
        13127500.,  11086200.,  10149000.,  17184100.,  18949000.,
        29144500.,  31162200.,  23994700.,  17853500.,  13572000.,
        14395400.,  16290300.,  21521000.,  17885200.,  16188000.,
        19504300.,  12718000.,  16192700.,  18138800.,  16824200.])


In [12]:
c  # 收盘价

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67,  351.99])

In [13]:
v  # 成交量

array([ 21144800.,  13473000.,  15236800.,   9242600.,  14064100.,
        11494200.,  17322100.,  13608500.,  17240800.,  33162400.,
        13127500.,  11086200.,  10149000.,  17184100.,  18949000.,
        29144500.,  31162200.,  23994700.,  17853500.,  13572000.,
        14395400.,  16290300.,  21521000.,  17885200.,  16188000.,
        19504300.,  12718000.,  16192700.,  18138800.,  16824200.])

In [14]:
vwap = np.average(c, weights=v, returned=True)
vwap, np.sum(v)

((350.58954935320088, 521869900.0), 521869900.0)

In [15]:
help(np.average)

Help on function average in module numpy.lib.function_base:

average(a, axis=None, weights=None, returned=False)
    Compute the weighted average along the specified axis.
    
    Parameters
    ----------
    a : array_like
        Array containing data to be averaged. If `a` is not an array, a
        conversion is attempted.
    axis : int, optional
        Axis along which to average `a`. If `None`, averaging is done over
        the flattened array.
    weights : array_like, optional
        An array of weights associated with the values in `a`. Each value in
        `a` contributes to the average according to its associated weight.
        The weights array can either be 1-D (in which case its length must be
        the size of `a` along the given axis) or of the same shape as `a`.
        If `weights=None`, then all data in `a` are assumed to have a
        weight equal to one.
    returned : bool, optional
        Default is `False`. If `True`, the tuple (`average`, `sum_of_we

In [16]:
help(np.mean)

Help on function mean in module numpy.core.fromnumeric:

mean(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in 

In [17]:
len(c)

30

In [18]:
t = np.arange(len(c))
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [19]:
np.average(c, weights=t)

352.42832183908041

In [20]:
vwap

(350.58954935320088, 521869900.0)

In [21]:
h, l = np.loadtxt('data.csv', delimiter=',', usecols=(4, 5), unpack=True)
print('h = %r \n l = %r' % (h, l))

h = array([ 344.4 ,  340.04,  345.65,  345.25,  344.24,  346.7 ,  353.25,
        355.52,  359.  ,  360.  ,  357.8 ,  359.48,  359.97,  364.9 ,
        360.27,  359.5 ,  345.4 ,  344.64,  345.15,  348.43,  355.05,
        355.72,  354.35,  359.79,  360.29,  361.67,  357.4 ,  354.76,
        349.77,  352.32]) 
 l = array([ 333.53,  334.3 ,  340.98,  343.55,  338.55,  343.51,  347.64,
        352.15,  354.87,  348.  ,  353.54,  356.71,  357.55,  360.5 ,
        356.52,  349.52,  337.72,  338.61,  338.37,  344.8 ,  351.12,
        347.68,  348.4 ,  355.92,  357.75,  351.31,  352.25,  350.6 ,
        344.9 ,  345.  ])


In [22]:
np.max(h)

364.89999999999998

In [23]:
np.min(l)

333.52999999999997

In [24]:
help(np.max)

Help on function amax in module numpy.core.fromnumeric:

amax(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the maximum of an array or maximum along an axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to operate.  By default, flattened input is
        used.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, the maximum is selected over multiple axes,
        instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternative output array in which to place the result.  Must
        be of the same shape and buffer length as the expected output.
        See `doc.ufuncs` (Section "Output arguments") for more details.
    
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,


In [25]:
np.ptp(h)

24.859999999999957

In [26]:
help(np.ptp)

Help on function ptp in module numpy.core.fromnumeric:

ptp(a, axis=None, out=None)
    Range of values (maximum - minimum) along an axis.
    
    The name of the function comes from the acronym for 'peak to peak'.
    
    Parameters
    ----------
    a : array_like
        Input values.
    axis : int, optional
        Axis along which to find the peaks.  By default, flatten the
        array.
    out : array_like
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type of the output values will be cast if necessary.
    
    Returns
    -------
    ptp : ndarray
        A new array holding the result, unless `out` was
        specified, in which case a reference to `out` is returned.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.ptp(x, axis=0)
    array([2, 2])
    
    >>> np.ptp(x, axis=

In [27]:
h.reshape(1, 30)

array([[ 344.4 ,  340.04,  345.65,  345.25,  344.24,  346.7 ,  353.25,
         355.52,  359.  ,  360.  ,  357.8 ,  359.48,  359.97,  364.9 ,
         360.27,  359.5 ,  345.4 ,  344.64,  345.15,  348.43,  355.05,
         355.72,  354.35,  359.79,  360.29,  361.67,  357.4 ,  354.76,
         349.77,  352.32]])

In [28]:
c = np.loadtxt('data.csv', delimiter=',', usecols=(6, ), unpack=True)

In [29]:
c

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56,  338.61,  342.62,  342.88,  348.16,  353.21,
        349.31,  352.12,  359.56,  360.  ,  355.36,  355.76,  352.47,
        346.67,  351.99])

In [31]:
m = np.median(c, axis=0, overwrite_input=True)
print ('c = %r \n median = %r' % (c, m))

c = array([ 339.32,  336.1 ,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        346.67,  349.31,  348.16,  342.88,  342.62,  338.61,  350.56,
        351.99,  352.12,  359.9 ,  359.18,  356.85,  354.54,  353.21,
        358.16,  358.3 ,  359.56,  360.  ,  355.36,  355.76,  352.47,
        355.2 ,  363.13]) 
 median = 352.05500000000001


In [34]:
np.msort(c)

array([ 336.1 ,  338.61,  339.32,  342.62,  342.88,  343.44,  344.32,
        345.03,  346.5 ,  346.67,  348.16,  349.31,  350.56,  351.88,
        351.99,  352.12,  352.47,  353.21,  354.54,  355.2 ,  355.36,
        355.76,  356.85,  358.16,  358.3 ,  359.18,  359.56,  359.9 ,
        360.  ,  363.13])

In [35]:
c 

array([ 339.32,  336.1 ,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        346.67,  349.31,  348.16,  342.88,  342.62,  338.61,  350.56,
        351.99,  352.12,  359.9 ,  359.18,  356.85,  354.54,  353.21,
        358.16,  358.3 ,  359.56,  360.  ,  355.36,  355.76,  352.47,
        355.2 ,  363.13])

In [37]:
np.var(c)

50.126517888888884

In [39]:
c

array([ 339.32,  336.1 ,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        346.67,  349.31,  348.16,  342.88,  342.62,  338.61,  350.56,
        351.99,  352.12,  359.9 ,  359.18,  356.85,  354.54,  353.21,
        358.16,  358.3 ,  359.56,  360.  ,  355.36,  355.76,  352.47,
        355.2 ,  363.13])

In [40]:
help(np.diff)

Help on function diff in module numpy.lib.function_base:

diff(a, n=1, axis=-1)
    Calculate the n-th discrete difference along given axis.
    
    The first difference is given by ``out[n] = a[n+1] - a[n]`` along
    the given axis, higher differences are calculated by using `diff`
    recursively.
    
    Parameters
    ----------
    a : array_like
        Input array
    n : int, optional
        The number of times values are differenced.
    axis : int, optional
        The axis along which the difference is taken, default is the last axis.
    
    Returns
    -------
    diff : ndarray
        The n-th differences. The shape of the output is the same as `a`
        except along `axis` where the dimension is smaller by `n`.
    
    See Also
    --------
    gradient, ediff1d, cumsum
    
    Examples
    --------
    >>> x = np.array([1, 2, 4, 7, 0])
    >>> np.diff(x)
    array([ 1,  2,  3, -7])
    >>> np.diff(x, n=2)
    array([  1,   1, -10])
    
    >>> x = np.array([[

In [45]:
returns = np.diff(c) / c[ : -1]
returns

array([-0.00948957,  0.02656947, -0.00205779, -0.00255576,  0.00890985,
        0.0155267 , -0.01480618,  0.00761531, -0.0032922 , -0.01516544,
       -0.00075828, -0.01170393,  0.03529134,  0.00407919,  0.00036933,
        0.02209474, -0.00200056, -0.006487  , -0.00647331, -0.00375134,
        0.01401433,  0.00039089,  0.00351661,  0.00122372, -0.01288889,
        0.00112562, -0.00924781,  0.00774534,  0.02232545])

In [46]:
print('Standard deviation = ', np.std(returns))

Standard deviation =  0.0124395299496


In [66]:
logreturns = np.diff( np.log(c) )
logreturns

array([-0.00953488,  0.02622264, -0.00205991, -0.00255903,  0.00887039,
        0.01540739, -0.01491689,  0.00758646, -0.00329764, -0.01528161,
       -0.00075857, -0.01177296,  0.03468287,  0.00407089,  0.00036926,
        0.02185419, -0.00200256, -0.00650813, -0.00649435, -0.00375839,
        0.01391703,  0.00039081,  0.00351044,  0.00122297, -0.01297267,
        0.00112499, -0.00929083,  0.0077155 ,  0.02207989])

In [74]:
returns > 0

array([False,  True, False, False,  True,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True,  True,  True, False,  True, False,
        True,  True], dtype=bool)

In [71]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x` and `y` need to have the same
        shape as `condition`.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are 1-D, `wh

In [81]:
arr1 = np.arange(5) * 2
arr2 = np.arange(5) * 3
np.where([False], arr1, arr2)

array([ 0,  3,  6,  9, 12])

In [83]:
annual_velatility = np.std(logreturns) / np.mean(logreturns) / np.sqrt(1./252.)
print(annual_velatility)

83.8137811829


In [89]:
from datetime import datetime

def datestr2num(s):
    return datetime.strptime(s.decode(), '%d-%m-%Y').weekday()

In [90]:
dates, close = np.loadtxt('data.csv', delimiter=',', usecols=(1,6), converters={1: datestr2num}, unpack=True)

In [92]:
dates

array([ 4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,  1.,
        2.,  3.,  4.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.,  0.,
        1.,  2.,  3.,  4.])

In [93]:
averages = np.zeros(5)

In [96]:
for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print('Day', i, 'prices', prices, 'avg', avg)
    averages[i] = avg

Day 0 prices [[ 339.32  351.88  359.18  353.21  355.36]] avg 351.79
Day 1 prices [[ 345.03  355.2   359.9   338.61  349.31  355.76]] avg 350.635
Day 2 prices [[ 344.32  358.16  363.13  342.62  352.12  352.47]] avg 352.136666667
Day 3 prices [[ 343.44  354.54  358.3   342.88  359.56  346.67]] avg 350.898333333
Day 4 prices [[ 336.1   346.5   356.85  350.56  348.16  360.    351.99]] avg 350.022857143


In [112]:
top = np.max(averages)
print('Highest average', top)
print('Top day of the week', np.argmax(averages))
bottom = np.min(averages)
print('Lowest average', bottom)
print('Bottom day of the week', np.argmin(averages))

Highest average 352.136666667
Top day of the week 2
Lowest average 350.022857143
Bottom day of the week 4


In [113]:
help(np.argmax)

Help on function argmax in module numpy.core.fromnumeric:

argmax(a, axis=None, out=None)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    
    Notes
    -----
    In case of multiple occurrences of the maximum values, the indices
    corresponding to the first occurrence ar

In [115]:
help(averages.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [116]:
import numpy as np
from datetime import datetime

def datestr2num(b):
    return datetime.strptime(b.decode(), '%d-%m-%Y').date().weekday()

dates, close = np.loadtxt('data.csv', delimiter=',', usecols=(1, 6), converters={1: datestr2num}, unpack=True)
print('Dates =', dates)

averages = np.zeros(5)

for i in range(5):
    indices = np.where(dates == i)
    prices = np.take(close, indices)
    avg = np.mean(prices)
    print('Day', i, 'prices', prices, 'Average', avg)
    averages[i] = avg

top = np.max(averages)
print('Highest average', top)
print('Top day of the week', np.argmax(averages))

bottom = np.min(averages)
print('Lowest average', bottom)
print('Bottom day of the week', np.argmin(averages))

Dates = [ 4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.  1.  2.
  3.  4.  0.  1.  2.  3.  4.  0.  1.  2.  3.  4.]
Day 0 prices [[ 339.32  351.88  359.18  353.21  355.36]] Average 351.79
Day 1 prices [[ 345.03  355.2   359.9   338.61  349.31  355.76]] Average 350.635
Day 2 prices [[ 344.32  358.16  363.13  342.62  352.12  352.47]] Average 352.136666667
Day 3 prices [[ 343.44  354.54  358.3   342.88  359.56  346.67]] Average 350.898333333
Day 4 prices [[ 336.1   346.5   356.85  350.56  348.16  360.    351.99]] Average 350.022857143
Highest average 352.136666667
Top day of the week 2
Lowest average 350.022857143
Bottom day of the week 4


In [117]:
!more data.csv

AAPL,28-01-2011, ,344.17,344.4,333.53,336.1,21144800
AAPL,31-01-2011, ,335.8,340.04,334.3,339.32,13473000
AAPL,01-02-2011, ,341.3,345.65,340.98,345.03,15236800
AAPL,02-02-2011, ,344.45,345.25,343.55,344.32,9242600
AAPL,03-02-2011, ,343.8,344.24,338.55,343.44,14064100
AAPL,04-02-2011, ,343.61,346.7,343.51,346.5,11494200
AAPL,07-02-2011, ,347.89,353.25,347.64,351.88,17322100
AAPL,08-02-2011, ,353.68,355.52,352.15,355.2,13608500
AAPL,09-02-2011, ,355.19,359,354.87,358.16,17240800
AAPL,10-02-2011, ,357.39,360,348,354.54,33162400
AAPL,11-02-2011, ,354.75,357.8,353.54,356.85,13127500
AAPL,14-02-2011, ,356.79,359.48,356.71,359.18,11086200
AAPL,15-02-2011, ,359.19,359.97,357.55,359.9,10149000
AAPL,16-02-2011, ,360.8,364.9,360.5,363.13,17184100
AAPL,17-02-2011, ,357.1,360.27,356.52,358.3,18949000
AAPL,18-02-2011, ,358.21,359.5,349.52,350.56,29144500
AAPL,22-02-2011, ,342.05,345.4,337.72,338.61,31162200
AAPL,23-02-2011, ,338.77,344.64,338.61,342.62,23994700
AAPL,24-02-2011, ,344.02,345.15,338.37

In [118]:
close = close[:16]
dates = dates[:16]

In [119]:
close

array([ 336.1 ,  339.32,  345.03,  344.32,  343.44,  346.5 ,  351.88,
        355.2 ,  358.16,  354.54,  356.85,  359.18,  359.9 ,  363.13,
        358.3 ,  350.56])

In [130]:
first_monday = np.ravel(np.where(dates == 0))[0]
print('The first Monday index is', first_monday)

The first Monday index is 1


In [134]:
last_friday = np.ravel(np.where(dates == 4))[-1]
print('The last Friday index is', last_friday)

The last Friday index is 15


In [140]:
weeks_indices = np.arange(first_monday, last_friday + 1)
print('Weeks indices initial', weeks_indices)

Weeks indices initial [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [141]:
weeks_indices = np.split(weeks_indices, 3)
print('Week indices after split', weeks_indices)

Week indices after split [array([1, 2, 3, 4, 5], dtype=int64), array([ 6,  7,  8,  9, 10], dtype=int64), array([11, 12, 13, 14, 15], dtype=int64)]


In [144]:
def summarize(a, o, h, l, c):
    monday_open = o[a[0]]
    week_high = np.max(np.take(h, a))
    week_low = np.min(np.take(l, a))
    friday_close = c[a[-1]]
    return ('APPL', monday_open, week_high, week_low, friday_close)


In [ ]:
weeksummary = np.apply_along_axis(summarize, 1, weeks_indices, open, high, low, close)

In [147]:
!start .

In [149]:
import numpy as np
from datetime import datetime

# Monday 0
# Tuesday 1
# Wednesday 2
# Thursday 3
# Friday 4
# Saturday 5
# Sunday 6
def datestr2num(s):
   return datetime.strptime(s.decode(), "%d-%m-%Y").date().weekday()

dates, open, high, low, close = np.loadtxt('data.csv', delimiter=',', usecols=(1, 3, 4, 5, 6), converters={1: datestr2num}, unpack=True)
close = close[:16]
dates = dates[:16]

# get first Monday
first_monday = np.ravel(np.where(dates == 0))[0]
print("The first Monday index is", first_monday)

# get last Friday
last_friday = np.ravel(np.where(dates == 4))[-1]
print("The last Friday index is", last_friday)

weeks_indices = np.arange(first_monday, last_friday + 1)
print("Weeks indices initial", weeks_indices)

weeks_indices = np.split(weeks_indices, 3)
print("Weeks indices after split", weeks_indices)

def summarize(a, o, h, l, c):
    monday_open = o[a[0]]
    week_high = np.max( np.take(h, a) )
    week_low = np.min( np.take(l, a) )
    friday_close = c[a[-1]]

    return("APPL", monday_open, week_high, week_low, friday_close)

weeksummary = np.apply_along_axis(summarize, 1, weeks_indices, open, high, low, close)
print("Week summary", weeksummary)

np.savetxt("weeksummary.csv", weeksummary, delimiter=",", fmt="%s")


The first Monday index is 1
The last Friday index is 15
Weeks indices initial [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Weeks indices after split [array([1, 2, 3, 4, 5], dtype=int64), array([ 6,  7,  8,  9, 10], dtype=int64), array([11, 12, 13, 14, 15], dtype=int64)]
Week summary [['APPL' '335.8' '346.7' '334.3' '346.5']
 ['APPL' '347.8' '360.0' '347.6' '356.8']
 ['APPL' '356.7' '364.9' '349.5' '350.5']]


In [158]:

b = np.apply_along_axis(summarize, 1, weeks_indices, open, high, low, close)

In [159]:

a = []
a = [summarize(x, open, high, low, close) for x in weeks_indices]

In [163]:
for x in weeks_indices:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [161]:
a

[('APPL', 335.80000000000001, 346.69999999999999, 334.30000000000001, 346.5),
 ('APPL', 347.88999999999999, 360.0, 347.63999999999999, 356.85000000000002),
 ('APPL', 356.79000000000002, 364.89999999999998, 349.51999999999998, 350.56)]

In [162]:
b

array([['APPL', '335.8', '346.7', '334.3', '346.5'],
       ['APPL', '347.8', '360.0', '347.6', '356.8'],
       ['APPL', '356.7', '364.9', '349.5', '350.5']], 
      dtype='<U5')

In [164]:
help(np.maximum)

Help on ufunc object:

maximum = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(X, Y

In [165]:
np.info(np.maximum)

maximum(x1, x2[, out])

Element-wise maximum of array elements.

Compare two arrays and returns a new array containing the element-wise
maxima. If one of the elements being compared is a NaN, then that
element is returned. If both elements are NaNs then the first is
returned. The latter distinction is important for complex NaNs, which
are defined as at least one of the real or imaginary parts being a NaN.
The net effect is that NaNs are propagated.

Parameters
----------
x1, x2 : array_like
    The arrays holding the elements to be compared. They must have
    the same shape, or shapes that can be broadcast to a single shape.

Returns
-------
y : ndarray or scalar
    The maximum of `x1` and `x2`, element-wise.  Returns scalar if
    both  `x1` and `x2` are scalars.

See Also
--------
minimum :
    Element-wise minimum of two arrays, propagates NaNs.
fmax :
    Element-wise maximum of two arrays, ignores NaNs.
amax :
    The maximum value of an array along a given axis, propagates NaNs