## 2. NumPy 基础

### 2.1 NumPy 数组对象

`ndarray`: NumPy中的多维数组对象。

* 由**实际数据**和**元数据**组成。

* 大部分数组操作改变的是元数据。

* NumPy数组一般是同质的：所有元素类型一致。

使用`arange()`创建数组：

> `arange()`创建一个值平均分布的数组。

In [1]:
import numpy as np
a = np.arange(5)

使用`dtype()`查看数组的数据类型：

> `ndarray.dtype`是ndarray数组的数据类型。

In [2]:
a.dtype

dtype('int32')

使用`shape`查看数组的维度：

> `ndarray.shape`是一个tuple，tuple中的元素即为这个数组在每一个维度上的大小。

In [3]:
a.shape

(5,)

### 2.2 创建多维数组

创建多维数组，并显示其维度：

> `array()`函数根据给定的对象生成NumPy数组。给定的对象应该是“类数组”的(array-like)。Python中的list就可以。

In [4]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [5]:
m.shape

(2, 2)

创建一个3×3多维数组：

In [6]:
mat = np.array([np.arange(3), np.arange(3), np.arange(3)])
mat

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
mat.shape

(3, 3)

选取数组中的某个特定元素：

In [11]:
a = np.array([ [1, 2], [3, 4] ])
a

array([[1, 2],
       [3, 4]])